version: "3.8"

services:
    mongodb:
        container_name: mongo
        image: mongo:latest
        restart: on-failure
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: secret
        volumes:
            - E:\ReactProjects\booking\server\database_data:/data/db
        ports:
            - "27017:27017"
